/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Affinity
#define HEADER_Affinity

#include "config.h"
#include <stdlib.h>


typedef struct Affinity_ {
   int size;
   int used;
   int* cpus;
} Affinity;


Affinity* Affinity_new();

void Affinity_delete(Affinity* this);

void Affinity_add(Affinity* this, int id);


#endif
