/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_CRT
#define HEADER_CRT
/*
htop
(C) 2004 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/


#include <curses.h>
#include <signal.h>
#include <stdlib.h>
#include <stdbool.h>

#include "debug.h"

#define WHITE_PAIR 0
#define BLUE_PAIR 1
#define GREEN_PAIR 2
#define RED_PAIR 3
#define BROWN_PAIR 4
#define CYAN_PAIR 5
#define BLACK_PAIR 6

#define HEADER_PAIR 7
#define INVERSE_PAIR 8
#define FUNCTIONBAR_PAIR 9

#define MIN_UPDATE_SLICE 15

//#link curses

bool CRT_hasColors;

void CRT_init();

void CRT_done();

int CRT_readKey();

void CRT_handleSIGSEGV(int signal);

void CRT_handleSIGTERM(int signal);

#endif
