/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_FunctionBar
#define HEADER_FunctionBar
/*
htop
(C) 2004 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "CRT.h"

#include "debug.h"
#include <assert.h>

#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <curses.h>


typedef struct FunctionBar_ {
   int size;
   char** functions;
   char** keys;
   int* events;
} FunctionBar;




FunctionBar* FunctionBar_new(int size, char** functions, char** keys, int* events);

void FunctionBar_delete(FunctionBar* this);

void FunctionBar_draw(FunctionBar* this, char* buffer);

void FunctionBar_drawAttr(FunctionBar* this, char* buffer, int attr);

int FunctionBar_synthesizeEvent(FunctionBar* this, int pos);

#endif
