/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_ListBox
#define HEADER_ListBox
/*
htop
(C) 2004 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Object.h"
#include "TypedVector.h"
#include "CRT.h"
#include "RichString.h"

#include "debug.h"

#include <assert.h>
#include <math.h>
#include <sys/param.h>
#include <stdbool.h>

#include <curses.h>
//#link curses

typedef struct ListBox_ {
   int x, y, w, h;
   WINDOW* window;
   TypedVector* items;
   int selected;
   int scrollV, scrollH;
   int oldSelected;
   bool needsRedraw;
   RichString header;
} ListBox;

ListBox* ListBox_new(int x, int y, int w, int h, char* type);

void ListBox_setHeader(ListBox* this, RichString header);

void ListBox_delete(ListBox* this);

void ListBox_move(ListBox* this, int x, int y);

void ListBox_resize(ListBox* this, int w, int h);

void ListBox_prune(ListBox* this);

void ListBox_add(ListBox* this, Object* o);

void ListBox_set(ListBox* this, int i, Object* o);

Object* ListBox_get(ListBox* this, int i);

Object* ListBox_getSelected(ListBox* this);

int ListBox_getSelectedIndex(ListBox* this);

int ListBox_getSize(ListBox* this);

void ListBox_setSelected(ListBox* this, int selected);

void ListBox_draw(ListBox* this);

void ListBox_onKey(ListBox* this, int key);

#endif
