/* Do not edit this file. It was automatically genarated. */

#ifndef HEADER_RichString
#define HEADER_RichString


#include <stdlib.h>
#include <string.h>
#include <curses.h>
#include <assert.h>
#include <sys/param.h>

#include "debug.h"

#define RICHSTRING_MAXLEN 512


typedef struct RichString_ {
   int len;
   chtype chstr[RICHSTRING_MAXLEN+1];
} RichString;



RichString RichString_new();

void RichString_delete(RichString this);

void RichString_prune(RichString* this);

void RichString_attrOn(int attrs);

void RichString_attrOff(int attrs);

void RichString_write(RichString* this, int attrs, char* data);

void RichString_append(RichString* this, int attrs, char* data);

void RichString_setAttr(RichString *this, int attrs);

void RichString_applyAttr(RichString *this, int attrs);

#endif
